apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myexpress
  name: myexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myexpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myexpress
    spec:
      containers:
      - image: onyeechris/express_workflow:latest
        name: myexpress
        ports:
        - containerPort: 3000
        resources: {}
status: {}

