      labels:
        app: myexpress
    spec:
      containers:
      - image: docker.io/onyeechris/express-new:1.0
        name: sha256
        ports:
        - containerPort: 3000
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: myexpress
spec:
  selector:
    app: myexpress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
