name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    
    - run: npm run build --if-present
    
    - name: build and push docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: onyeechris/express_workflow
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Add a step here to deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: kubectl apply -f deploy_express.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

