name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build:
    runs-on: ubuntu:latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    
    - run: npm run build --if-present
    
    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        push: false
        image: onyeechris/express_workflow
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: "self-hosted"
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Kubernetes
      
      run: kubectl apply -f deploy_express.yaml
