name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    
    - run: npm run build --if-present
    
    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        build_context: ./app.js
        dockerfile_path: ./Dockerfile
        image: onyeechris/express_workflow
        #registry: docker.io
        #username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Decode kubeconfig secret
      run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml

    - name: Set up kubectl
      run: |
        sudo apt-get update && sudo apt-get install -y kubectl
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deploy_express.yaml --validate=false
