name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:

  deploy:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v2
   
    - name: Deploy to Kubernetes
      uses: actions-hub/kubectl@master
      with:
        args: apply -f deploy_express.yaml
