name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  KUBE_CONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # Copy kubeconfig file to runner
    - name: Copy kubeconfig file
      run: cp ~/.kube/config $HOME/.kube/config

      # Set KUBECONFIG environment variable
    - name: Set KUBECONFIG
      run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
        kubectl apply -f deploy_express.yaml --validate=false
