name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
 deploy:
    runs-on: "self-hosted"
    steps:
    - uses: actions/checkout@v2
    - uses: actions-hub/kubectl@master
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy to Kubernetes
      run: kubectl apply -f deploy_express.yaml
